<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(VecxyPlatform)' == 'Desktop'">net10.0</TargetFramework>
    <TargetFramework Condition="'$(VecxyPlatform)' == 'Android' and '$(TargetFramework)' == ''">net10.0-android</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vecxy.Engine\Vecxy.Engine.csproj" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>
