<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(VecxyPlatform)' == 'Desktop'">net10.0</TargetFramework>
    <TargetFramework Condition="'$(VecxyPlatform)' == 'Android'">net10.0-android</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vecxy.Engine\Vecxy.Engine.csproj" />
  </ItemGroup>
</Project>
