<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AssemblyName>Vecxy.CLI</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Vecxy.Assets\Vecxy.Assets.csproj" />
	  <ProjectReference Include="..\Vecxy.Diagnostics\Vecxy.Diagnostics.csproj" />
	</ItemGroup>
</Project>
