<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <ProjectReference Include="..\Vecxy.Diagnostics\Vecxy.Diagnostics.csproj" />
    <ProjectReference Include="..\Vecxy.Kernel\Vecxy.Kernel.csproj" />
  </ItemGroup>
</Project>
