<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
      <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
      <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
      <PackageReference Include="Yoga.Net" Version="3.2.3" />
      <PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.23.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Vecxy.Diagnostics\Vecxy.Diagnostics.csproj" />
      <ProjectReference Include="..\Vecxy.Kernel\Vecxy.Kernel.csproj" />
      <ProjectReference Include="..\Vecxy.Assets\Vecxy.Assets.csproj" />
      <ProjectReference Include="..\Vecxy.Scene\Vecxy.Scene.csproj" />
    </ItemGroup>
		
	
</Project>
