<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <TargetFramework></TargetFramework>
      <TargetFrameworks>net10.0;net10.0-android</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
      <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
      <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
      <PackageReference Include="Yoga.Net" Version="3.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Vecxy.Diagnostics\Vecxy.Diagnostics.csproj" />
      <ProjectReference Include="..\Vecxy.Kernel\Vecxy.Kernel.csproj" />
      <ProjectReference Include="..\Vecxy.Assets\Vecxy.Assets.csproj" />
      <ProjectReference Include="..\Vecxy.Scene\Vecxy.Scene.csproj" />
    </ItemGroup>
		
	
</Project>
