<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Vecxy.Assets\Vecxy.Assets.csproj" />
      <ProjectReference Include="..\Vecxy.Diagnostics\Vecxy.Diagnostics.csproj" />
      <ProjectReference Include="..\Vecxy.Kernel\Vecxy.Kernel.csproj" />
    </ItemGroup>
</Project>
