<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <ProjectReference Include="..\Vecxy.Assets\Vecxy.Assets.csproj" />
      <ProjectReference Include="..\Vecxy.Audio\Vecxy.Audio.csproj" />
      <ProjectReference Include="..\Vecxy.Input\Vecxy.Input.csproj" />
      <ProjectReference Include="..\Vecxy.Kernel\Vecxy.Kernel.csproj" />
      <ProjectReference Include="..\Vecxy.Physics\Vecxy.Physics.csproj" />
      <ProjectReference Include="..\Vecxy.Rendering\Vecxy.Rendering.csproj" />
      <ProjectReference Include="..\Vecxy.Scene\Vecxy.Scene.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <Content Include="Assets\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>Assets\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
        </Content>
    </ItemGroup>
</Project>
