<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework Condition="'$(VecxyPlatform)' == 'Desktop'">net10.0</TargetFramework>
        <TargetFramework Condition="'$(VecxyPlatform)' == 'Android' and '$(TargetFramework)' == ''">net10.0-android</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="StbImageSharp" Version="2.30.15" />
      <ProjectReference Include="..\Vecxy.Assets\Vecxy.Assets.csproj" />
      <ProjectReference Include="..\Vecxy.Audio\Vecxy.Audio.csproj" />
      <ProjectReference Include="..\Vecxy.Input\Vecxy.Input.csproj" />
      <ProjectReference Include="..\Vecxy.Kernel\Vecxy.Kernel.csproj" />
      <ProjectReference Include="..\Vecxy.Messaging\Vecxy.Messaging.csproj" />
      <ProjectReference Include="..\Vecxy.Physics\Vecxy.Physics.csproj" />
      <ProjectReference Include="..\Vecxy.Rendering\Vecxy.Rendering.csproj" />
      <ProjectReference Include="..\Vecxy.Scene\Vecxy.Scene.csproj" />
      <ProjectReference Include="..\Vecxy.UI\Vecxy.UI.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <Content Include="Assets\**\*" Condition="'$(TargetPlatformIdentifier)' != 'android' and '$(VecxyPackagesDirectory)' == ''">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>Assets\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
        </Content>
    </ItemGroup>
</Project>
