<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Vecxy.Diagnostics\Vecxy.Diagnostics.csproj" />
    <ProjectReference Include="..\Vecxy.Kernel\Vecxy.Kernel.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
		<PackageReference Include="StbImageSharp" Version="2.30.15" />
		<PackageReference Include="glTF2Loader" Version="2.0.0-preview.14" />
		<PackageReference Include="YamlDotNet" Version="16.3.0" />
	</ItemGroup>
</Project>
