using System.Text;
using Vecxy.Assets;

namespace Vecxy.Input.Generator;

internal static class Program
{
    public static int Main(string[] args)
    {
        if (args.Length < 2)
        {
            Console.Error.WriteLine(
                "Usage: Vecxy.Input.Generator <output-dir> <input-files...>");
            return 1;
        }

        var outputDirectory = Path.GetFullPath(args[0]);
        Directory.CreateDirectory(outputDirectory);

        foreach (var oldFile in Directory.EnumerateFiles(outputDirectory, "*.g.cs"))
            File.Delete(oldFile);

        for (var index = 1; index < args.Length; index++)
        {
            var path = Path.GetFullPath(args[index]);
            var definition = Load(path);
            var code = Generate(definition, path);
            var fileName = Path.GetFileNameWithoutExtension(path) + ".g.cs";
            File.WriteAllText(
                Path.Combine(outputDirectory, fileName),
                code,
                Encoding.UTF8);
        }

        return 0;
    }

    private static InputAsset Load(string path)
    {
        var definition = InputAssetReader.ReadFromFile(path);
        Validate(definition, path);
        return definition;
    }

    private static void Validate(InputAsset definition, string path)
    {
        if (string.IsNullOrWhiteSpace(definition.Namespace))
            throw new InvalidDataException($"Input namespace is empty: {path}");

        if (string.IsNullOrWhiteSpace(definition.ClassName))
            throw new InvalidDataException($"Input className is empty: {path}");

        foreach (var map in definition.Maps)
        {
            if (string.IsNullOrWhiteSpace(map.Name))
                throw new InvalidDataException($"Input map name is empty: {path}");

            var actionNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (var action in map.Actions)
            {
                if (!actionNames.Add(action.Name))
                {
                    throw new InvalidDataException(
                        $"Duplicate input action '{map.Name}.{action.Name}': {path}");
                }

                if (action.Type is not (EInputActionType.Button or EInputActionType.Vector2))
                {
                    throw new InvalidDataException(
                        $"Unsupported action type '{action.Type}' for '{map.Name}.{action.Name}': {path}");
                }

                foreach (var binding in action.Bindings)
                    ValidateBinding(map, action, binding, path);
            }
        }
    }

    private static void ValidateBinding(
        InputMapAsset map,
        InputActionAsset action,
        InputBindingAsset binding,
        string path)
    {
        switch (binding.Type)
        {
            case EInputBindingType.Keyboard:
                if (binding.Key == EKeyboardKey.Undefined)
                {
                    throw new InvalidDataException(
                        $"Unsupported key '{binding.Key}' for '{map.Name}.{action.Name}': {path}");
                }

                if (action.Type != EInputActionType.Button)
                {
                    throw new InvalidDataException(
                        $"Keyboard binding currently supports only Button actions: '{map.Name}.{action.Name}' in {path}");
                }

                break;

            case EInputBindingType.Mouse:
                if (binding.Mouse == EMouseButton.Undefined)
                {
                    throw new InvalidDataException(
                        $"Unsupported mouse button '{binding.Mouse}' for '{map.Name}.{action.Name}': {path}");
                }

                if (action.Type != EInputActionType.Button)
                {
                    throw new InvalidDataException(
                        $"Mouse binding currently supports only Button actions: '{map.Name}.{action.Name}' in {path}");
                }

                break;

            case EInputBindingType.Composite:
                if (!string.Equals(binding.Composite, "WASD", StringComparison.Ordinal))
                {
                    throw new InvalidDataException(
                        $"Unsupported composite '{binding.Composite}' for '{map.Name}.{action.Name}': {path}");
                }

                if (action.Type != EInputActionType.Vector2)
                {
                    throw new InvalidDataException(
                        $"Composite binding '{binding.Composite}' requires Vector2 action: '{map.Name}.{action.Name}' in {path}");
                }

                break;

            default:
                throw new InvalidDataException(
                    $"Unsupported binding type '{binding.Type}' for '{map.Name}.{action.Name}': {path}");
        }
    }

    private static string Generate(InputAsset definition, string path)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine($"// Source: {path}");
        builder.AppendLine("using System.Numerics;");
        builder.AppendLine("using Vecxy.Assets;");
        builder.AppendLine("using Vecxy.Input;");
        builder.AppendLine();
        builder.AppendLine($"namespace {definition.Namespace};");
        builder.AppendLine();
        builder.AppendLine($"public static partial class {definition.ClassName}");
        builder.AppendLine("{");

        foreach (var map in definition.Maps)
        {
            builder.AppendLine($"    public sealed class {map.Name} : InputMap");
            builder.AppendLine("    {");

            foreach (var action in map.Actions)
            {
                var typeName =
                    action.Type == EInputActionType.Vector2
                        ? "InputAction<Vector2>"
                        : "InputAction";
                builder.AppendLine($"        public {typeName} {action.Name} {{ get; }}");
            }

            builder.AppendLine();
            builder.AppendLine($"        internal {map.Name}(IInputManager input)");
            builder.AppendLine($"            : base(input, \"{map.Name}\")");
            builder.AppendLine("        {");

            foreach (var action in map.Actions)
            {
                var createMethod =
                    action.Type == EInputActionType.Vector2
                        ? "CreateVector2Action"
                        : "CreateButtonAction";
                builder.AppendLine($"            {action.Name} = {createMethod}(nameof({action.Name}),");

                for (var index = 0; index < action.Bindings.Count; index++)
                {
                    var suffix = index == action.Bindings.Count - 1 ? ");" : ",";
                    builder.AppendLine($"                {RenderBinding(action.Bindings[index])}{suffix}");
                }
            }

            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderBinding(InputBindingAsset binding)
    {
        return binding.Type switch
        {
            EInputBindingType.Keyboard => $"InputBinding.Keyboard(EKeyboardKey.{binding.Key})",
            EInputBindingType.Mouse => $"InputBinding.Mouse(EMouseButton.{binding.Mouse})",
            EInputBindingType.Composite => "InputBinding.Composite(InputComposite.Wasd)",
            _ => throw new InvalidOperationException(
                $"Unsupported binding type '{binding.Type}'."),
        };
    }
}
