<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework Condition="'$(VecxyPlatform)' != 'Android'">net10.0</TargetFramework>
        <TargetFramework Condition="'$(VecxyPlatform)' == 'Android' and '$(TargetFramework)' == ''">net10.0-android</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Mediator.Net" Version="5.0.0" />
      <PackageReference Include="Mediator.Net.Autofac" Version="5.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Vecxy.Kernel\Vecxy.Kernel.csproj" />
    </ItemGroup>

</Project>
