<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <VecxyGenerateEntryPoint>true</VecxyGenerateEntryPoint>
    <VecxyApplicationId>tools.vecxy.spriteeditor</VecxyApplicationId>
    <VecxyApplicationTitle>Vecxy Sprite Editor</VecxyApplicationTitle>
  </PropertyGroup>
  <Import Project="../../Code/Vecxy.Platforms/build/Vecxy.Platforms.props" />
  <ItemGroup>
    <ProjectReference Include="../../Code/Vecxy.Engine/Vecxy.Engine.csproj" />
    <ProjectReference Include="../../Code/Vecxy.UI/Vecxy.UI.csproj" />
    <ProjectReference Include="../../Code/Vecxy.Assets/Vecxy.Assets.csproj" />
    <ProjectReference Include="../../Code/Vecxy.Rendering/Vecxy.Rendering.csproj" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>
</Project>
