<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Vecxy.Assets/Vecxy.Assets.csproj" />
    <ProjectReference Include="../Vecxy.Diagnostics/Vecxy.Diagnostics.csproj" />
    <ProjectReference Include="../Vecxy.Kernel/Vecxy.Kernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NuLua.Luau" Version="0.1.0" />
  </ItemGroup>
</Project>
