<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Vecxy.Kernel\Vecxy.Kernel.csproj"/>

        <None Include="../../FMODEngine/api/core/lib/x86_64/libfmod.so">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>libfmod.so</TargetPath>
        </None>
    </ItemGroup>


</Project>
