<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework Condition="'$(VecxyPlatform)' == 'Desktop'">net10.0</TargetFramework>
    <TargetFramework Condition="'$(VecxyPlatform)' == 'Android'">net10.0-android</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vecxy.UI\Vecxy.UI.csproj" />
  </ItemGroup>
</Project>
