<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Vecxy.Animations\Vecxy.Animations.csproj" />
    <ProjectReference Include="..\Vecxy.Assets\Vecxy.Assets.csproj" />
    <ProjectReference Include="..\Vecxy.Rendering\Vecxy.Rendering.csproj" />
    <ProjectReference Include="..\Vecxy.Scene\Vecxy.Scene.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\..\AnimationGame\Assets\Models\Fox.glb"
          Link="Assets\Models\Fox.glb"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
