<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ImGui.NET" Version="1.90.8.1" />
      <PackageReference Include="Silk.NET.OpenGL.Extensions.ImGui" Version="2.23.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Vecxy.Diagnostics\Vecxy.Diagnostics.csproj" />
      <ProjectReference Include="..\Vecxy.Engine\Vecxy.Engine.csproj" />
      <ProjectReference Include="..\Vecxy.Kernel\Vecxy.Kernel.csproj" />
      <ProjectReference Include="..\Vecxy.Physics\Vecxy.Physics.csproj" />
      <ProjectReference Include="..\Vecxy.Rendering\Vecxy.Rendering.csproj" />
      <ProjectReference Include="..\Vecxy.Scene\Vecxy.Scene.csproj" />
    </ItemGroup>

</Project>
